FROM python:3.13-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir -e .

COPY . .

{% if expose_port is defined %}
EXPOSE {{ expose_port }}
{% endif %}
CMD ["python", "-m", "{{ pkg_name }}"]
